apiVersion: apps/v1
kind: Deployment
metadata: { name: customer-service }
spec:
  replicas: 1
  selector: { matchLabels: { app: customer } }
  template:
    metadata: { labels: { app: customer } }
    spec:
      containers:
      - name: customer-service
        image: <ACR_LOGIN_SERVER>/customer_service:latest
        ports: [{ containerPort: 8000 }]
        env:
        - { name: POSTGRES_HOST, value: "customer-db" }
        - { name: POSTGRES_DB,   value: "customers" }
        - { name: POSTGRES_USER, value: "postgres" }
        - { name: POSTGRES_PASSWORD, value: "postgres" }
---
apiVersion: v1
kind: Service
metadata: { name: customer-service }
spec:
  selector: { app: customer }
  ports: [{ port: 8002, targetPort: 8000, protocol: TCP, name: http }]
  type: ClusterIP
