apiVersion: apps/v1
kind: Deployment
metadata: { name: order-service }
spec:
  replicas: 1
  selector: { matchLabels: { app: order } }
  template:
    metadata: { labels: { app: order } }
    spec:
      containers:
      - name: order-service
        image: <ACR_LOGIN_SERVER>/order_service:latest
        ports: [{ containerPort: 8000 }]
        env:
        - { name: POSTGRES_HOST, value: "order-db" }
        - { name: POSTGRES_DB,   value: "orders" }
        - { name: POSTGRES_USER, value: "postgres" }
        - { name: POSTGRES_PASSWORD, value: "postgres" }
        - { name: CUSTOMER_SERVICE_URL, value: "http://customer-service:8000" }
---
apiVersion: v1
kind: Service
metadata: { name: order-service }
spec:
  selector: { app: order }
  ports: [{ port: 8001, targetPort: 8000, protocol: TCP, name: http }]
  type: ClusterIP
