name: Stage 2 - Backend CD - Deploy to Staging

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NS: sit722-staging-${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group "${{ secrets.AKS_RESOURCE_GROUP }}" --name "${{ secrets.AKS_CLUSTER }}" --overwrite-existing

      - name: Create namespace
        run: kubectl create namespace "$NS" || true

      - name: Generate K8s manifests
        env:
          ACR: ${{ secrets.ACR_LOGIN_SERVER }}
        run: |
          mkdir -p k8s

          # Product service + DB
          cat > k8s/product.yaml <<YAML
          apiVersion: apps/v1
          kind: Deployment
          metadata: { name: product-service }
          spec:
            replicas: 1
            selector: { matchLabels: { app: product } }
            template:
              metadata: { labels: { app: product } }
              spec:
                containers:
                - name: product-service
                  image: ${ACR}/product_service:latest
                  ports: [{ containerPort: 8000 }]
                  env:
                  - { name: POSTGRES_HOST, value: "product-db" }
                  - { name: POSTGRES_DB,   value: "products" }
                  - { name: POSTGRES_USER, value: "postgres" }
                  - { name: POSTGRES_PASSWORD, value: "postgres" }
          ---
          apiVersion: v1
          kind: Service
          metadata: { name: product-service }
          spec:
            selector: { app: product }
            ports:
              - port: 8001
                targetPort: 8000
            type: LoadBalancer
          YAML

          # Customer service + DB
          cat > k8s/customer.yaml <<YAML
          apiVersion: apps/v1
          kind: Deployment
          metadata: { name: customer-service }
          spec:
            replicas: 1
            selector: { matchLabels: { app: customer } }
            template:
              metadata: { labels: { app: customer } }
              spec:
                containers:
                - name: customer-service
                  image: ${ACR}/customer_service:latest
                  ports: [{ containerPort: 8000 }]
                  env:
                  - { name: POSTGRES_HOST, value: "customer-db" }
                  - { name: POSTGRES_DB,   value: "customers" }
                  - { name: POSTGRES_USER, value: "postgres" }
                  - { name: POSTGRES_PASSWORD, value: "postgres" }
          ---
          apiVersion: v1
          kind: Service
          metadata: { name: customer-service }
          spec:
            selector: { app: customer }
            ports:
              - port: 8002
                targetPort: 8000
            type: LoadBalancer
          YAML

          # Order service + DB
          cat > k8s/order.yaml <<YAML
          apiVersion: apps/v1
          kind: Deployment
          metadata: { name: order-service }
          spec:
            replicas: 1
            selector: { matchLabels: { app: order } }
            template:
              metadata: { labels: { app: order } }
              spec:
                containers:
                - name: order-service
                  image: ${ACR}/order_service:latest
                  ports: [{ containerPort: 8000 }]
                  env:
                  - { name: POSTGRES_HOST, value: "order-db" }
                  - { name: POSTGRES_DB,   value: "orders" }
                  - { name: POSTGRES_USER, value: "postgres" }
                  - { name: POSTGRES_PASSWORD, value: "postgres" }
                  - { name: CUSTOMER_SERVICE_URL, value: "http://customer-service:8000" }
          ---
          apiVersion: v1
          kind: Service
          metadata: { name: order-service }
          spec:
            selector: { app: order }
            ports:
              - port: 8003
                targetPort: 8000
            type: LoadBalancer
          YAML

      - name: Apply manifests
        run: |
          kubectl apply -n "$NS" -f k8s/product.yaml
          kubectl apply -n "$NS" -f k8s/customer.yaml
          kubectl apply -n "$NS" -f k8s/order.yaml

      - name: Wait for External IPs
        run: |
          for i in {1..60}; do
            PRODUCT_IP=$(kubectl get svc product-service -n "$NS" -o jsonpath='{.status.loadBalancer.ingress[0].ip}' || true)
            CUSTOMER_IP=$(kubectl get svc customer-service -n "$NS" -o jsonpath='{.status.loadBalancer.ingress[0].ip}' || true)
            ORDER_IP=$(kubectl get svc order-service -n "$NS" -o jsonpath='{.status.loadBalancer.ingress[0].ip}' || true)

            if [ -n "$PRODUCT_IP" ] && [ -n "$CUSTOMER_IP" ] && [ -n "$ORDER_IP" ]; then
              echo "All IPs ready!"
              break
            fi
            echo "Waiting for LoadBalancer IPs... attempt $i"
            sleep 5
          done

          [ -n "$PRODUCT_IP" ] || { echo "::error::Product IP not found"; exit 1; }
          [ -n "$CUSTOMER_IP" ]|| { echo "::error::Customer IP not found"; exit 1; }
          [ -n "$ORDER_IP" ]   || { echo "::error::Order IP not found"; exit 1; }

          echo "PRODUCT_IP=$PRODUCT_IP" >> $GITHUB_ENV
          echo "CUSTOMER_IP=$CUSTOMER_IP" >> $GITHUB_ENV
          echo "ORDER_IP=$ORDER_IP" >> $GITHUB_ENV

      - name: Health checks
        run: |
          for u in "http://${PRODUCT_IP}:8001/health" "http://${CUSTOMER_IP}:8002/health" "http://${ORDER_IP}:8003/health"; do
            echo "GET $u"
            curl -sf "$u" || exit 1
          done

      - name: Teardown
        if: always()
        run: kubectl delete namespace "$NS"
