name: CI Pipeline - SIT722

on:
  push:
    branches:
      - testing

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports: ['5672:5672']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install test dependencies
        run: |
          pip install -r backend/product_service/requirements-dev.txt
          pip install -r backend/order_service/requirements-dev.txt
          pip install -r backend/customer_service/requirements-dev.txt

      - name: Run tests
        run: |
          pytest backend/product_service
          pytest backend/order_service
          pytest backend/customer_service

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Product Service
        uses: docker/build-push-action@v4
        with:
          context: ./backend/product_service
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/product_service:latest

      - name: Build and Push Order Service
        uses: docker/build-push-action@v4
        with:
          context: ./backend/order_service
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/order_service:latest

      - name: Build and Push Customer Service
        uses: docker/build-push-action@v4
        with:
          context: ./backend/customer_service
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
